name = "inshatech"
pages_build_output_dir = "."
compatibility_date = "2026-08-01"

[vars]
ENVIRONMENT = "production"
SUPABASE_URL = "https://uulqaslcfjrvkvyegmvo.supabase.co"
SYSTEM_NAME = "IINSHA TECH OS"
