/** IINSHA auth/session — fail-closed owner authentication. */
const ORIGINS=new Set(['https://inshatech.pages.dev','https://inshatech.com','https://www.inshatech.com','https://admin.inshatech.com']);
const cors=r=>{const o=r.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://inshatech.pages.dev','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Credentials':'true','Content-Type':'application/json','Cache-Control':'no-store'};};
const b64=s=>btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function sign(p,secret){if(!secret)throw Error('JWT_SECRET_NOT_CONFIGURED');const body=b64(JSON.stringify(p));const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=b64(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(body)))));return body+'.'+sig;}
async function totp(token,secret){if(!secret||!/^[0-9]{6}$/.test(String(token||'')))return false;const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const c=Math.floor(Date.now()/30000);for(let d=-1;d<=1;d++){const ab=new ArrayBuffer(8);new DataView(ab).setBigUint64(0,BigInt(c+d));const a=new Uint8Array(await crypto.subtle.sign('HMAC',k,ab)),o=a[a.length-1]&15,n=((a[o]&127)<<24|(a[o+1]<<16)|(a[o+2]<<8)|a[o+3])%1000000;if(String(n).padStart(6,'0')===String(token))return true;}return false;}
export async function onRequestPost({request,env={}}){const h=cors(request);try{for(const k of ['JWT_SECRET','ADMIN_PASSWORD_HASH','ADMIN_EMAIL','MFA_SECRET'])if(!env[k])return new Response(JSON.stringify({status:'CONFIGURATION_ERROR',error:`${k} is required`}),{status:503,headers:h});const b=await request.json().catch(()=>({}));if(b.refresh_token)return new Response(JSON.stringify({status:'REFRESH_REAUTH_REQUIRED'}),{status:401,headers:h});if(String(b.email||'').trim().toLowerCase()!==env.ADMIN_EMAIL.trim().toLowerCase()||await sha(String(b.password||''))!==env.ADMIN_PASSWORD_HASH)return new Response(JSON.stringify({status:'INVALID_CREDENTIALS'}),{status:401,headers:h});if(!(await totp(b.mfa_token,env.MFA_SECRET)))return new Response(JSON.stringify({status:'MFA_REQUIRED'}),{status:401,headers:h});const now=Math.floor(Date.now()/1000);const token=await sign({sub:env.ADMIN_EMAIL,role:'owner',hierarchy_level:1,mfa_verified:true,iat:now,exp:now+3600,jti:crypto.randomUUID()},env.JWT_SECRET);return new Response(JSON.stringify({status:'AUTHENTICATED',session_token:token,expires_in:3600,user:{email:env.ADMIN_EMAIL,role:'owner',hierarchy_level:1,mfa_verified:true}}),{status:200,headers:h});}catch(e){return new Response(JSON.stringify({status:'ERROR'}),{status:500,headers:h});}}
export function onRequestOptions({request}){return new Response(null,{status:204,headers:cors(request)});}
